package fvm

// NOTE: More opcodes are coming.
var opMap = map[string]OpCode{
	// Arithmetic
	"STOP": STOP,
	"ADD":  ADD,
	"SUB":  SUB,
	"MUL":  MUL,
	"DIV":  DIV,
	"EXP":  EXP,

	// Stack
	"POP":  POP,
	"DUP":  DUP,
	"SWAP": SWAP,

	// PUSH1 .. PUSH32
	"PUSH1":  PUSH1,
	"PUSH2":  PUSH2,
	"PUSH3":  PUSH3,
	"PUSH4":  PUSH4,
	"PUSH5":  PUSH5,
	"PUSH6":  PUSH6,
	"PUSH7":  PUSH7,
	"PUSH8":  PUSH8,
	"PUSH9":  PUSH9,
	"PUSH10": PUSH10,
	"PUSH11": PUSH11,
	"PUSH12": PUSH12,
	"PUSH13": PUSH13,
	"PUSH14": PUSH14,
	"PUSH15": PUSH15,
	"PUSH16": PUSH16,
	"PUSH17": PUSH17,
	"PUSH18": PUSH18,
	"PUSH19": PUSH19,
	"PUSH20": PUSH20,
	"PUSH21": PUSH21,
	"PUSH22": PUSH22,
	"PUSH23": PUSH23,
	"PUSH24": PUSH24,
	"PUSH25": PUSH25,
	"PUSH26": PUSH26,
	"PUSH27": PUSH27,
	"PUSH28": PUSH28,
	"PUSH29": PUSH29,
	"PUSH30": PUSH30,
	"PUSH31": PUSH31,
	"PUSH32": PUSH32,

	// Control flow
	"JMP":  JMP,
	"JMPI": JMPI,

	// Memory / Storage
	"MSTORE": MSTORE,
	"MLOAD":  MLOAD,
	"SSTORE": SSTORE,
	"SLOAD":  SLOAD,

	// Hashing / Crypto
	"SHA256": SHA256,

	// Environment / System
	"ADDRESS":        ADDRESS,
	"BALANCE":        BALANCE,
	"ORIGIN":         ORIGIN,
	"CALLER":         CALLER,
	"CALLVALUE":      CALLVALUE,
	"CALLDATALOAD":   CALLDATALOAD,
	"CALLDATASIZE":   CALLDATASIZE,
	"CALLDATACOPY":   CALLDATACOPY,
	"CODESIZE":       CODESIZE,
	"CODECOPY":       CODECOPY,
	"GASPRICE":       GASPRICE,
	"EXTCODESIZE":    EXTCODESIZE,
	"EXTCODECOPY":    EXTCODECOPY,
	"RETURNDATASIZE": RETURNDATASIZE,
	"RETURNDATACOPY": RETURNDATACOPY,
	"EXTCODEHASH":    EXTCODEHASH,
}
